(define x 2)
(define y 2)
(define func
    (lambda (n1 n2)
        (progn
            (ldefine y n2)
            (loop (> y -1)
                (ldefine x n1)
                (loop (> x -1)
                    (print y x)
                    (ldefine x (- x 1))
                )
                (ldefine y (- y 1))
            )
        )
    )
)
(func x y)
(print x y)
